// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Messages.pb.h"
// @@protoc_insertion_point(imports)

@class Barrage;
@class BarrageBuilder;
@class CourseInfo;
@class CourseInfoBuilder;
@class CourseList;
@class CourseListBuilder;
@class CourseType;
@class CourseTypeBuilder;
@class ImportMessage;
@class ImportMessageBuilder;
@class None;
@class NoneBuilder;
@class RegisterResult;
@class RegisterResultBuilder;
@class TestAllTypes;
@class TestAllTypesBuilder;
@class TestAllTypesNestedMessage;
@class TestAllTypesNestedMessageBuilder;
@class TestAllTypesOptionalGroup;
@class TestAllTypesOptionalGroupBuilder;
@class TestAllTypesRepeatedGroup;
@class TestAllTypesRepeatedGroupBuilder;
@class UserInfo;
@class UserInfoBuilder;



@interface ServicesRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end


// @@protoc_insertion_point(global_scope)
