// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Module.pb.h"
// @@protoc_insertion_point(imports)

@class Barrage;
@class BarrageBuilder;
@class CourseInfo;
@class CourseInfoBuilder;
@class CourseList;
@class CourseListBuilder;
@class CourseType;
@class CourseTypeBuilder;
@class ImportMessage;
@class ImportMessageBuilder;
@class None;
@class NoneBuilder;
@class RegisterResult;
@class RegisterResultBuilder;
@class TestAllTypes;
@class TestAllTypesBuilder;
@class TestAllTypesNestedMessage;
@class TestAllTypesNestedMessageBuilder;
@class TestAllTypesOptionalGroup;
@class TestAllTypesOptionalGroupBuilder;
@class TestAllTypesRepeatedGroup;
@class TestAllTypesRepeatedGroupBuilder;
@class UserInfo;
@class UserInfoBuilder;



@interface YingshibaoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define UserInfo_nickName @"nickName"
#define UserInfo_schoolName @"schoolName"
#define UserInfo_phone @"phone"
#define UserInfo_examType @"examType"
#define UserInfo_channelName @"channelName"
@interface UserInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNickName_:1;
  BOOL hasSchoolName_:1;
  BOOL hasPhone_:1;
  BOOL hasChannelName_:1;
  BOOL hasExamType_:1;
  NSString* nickName;
  NSString* schoolName;
  NSString* phone;
  NSString* channelName;
  UInt32 examType;
}
- (BOOL) hasNickName;
- (BOOL) hasSchoolName;
- (BOOL) hasPhone;
- (BOOL) hasExamType;
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* schoolName;
@property (readonly, strong) NSString* phone;
@property (readonly) UInt32 examType;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserInfoBuilder*) builder;
+ (UserInfoBuilder*) builder;
+ (UserInfoBuilder*) builderWithPrototype:(UserInfo*) prototype;
- (UserInfoBuilder*) toBuilder;

+ (UserInfo*) parseFromData:(NSData*) data;
+ (UserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserInfoBuilder : PBGeneratedMessageBuilder {
@private
  UserInfo* resultUserInfo;
}

- (UserInfo*) defaultInstance;

- (UserInfoBuilder*) clear;
- (UserInfoBuilder*) clone;

- (UserInfo*) build;
- (UserInfo*) buildPartial;

- (UserInfoBuilder*) mergeFrom:(UserInfo*) other;
- (UserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (UserInfoBuilder*) setNickName:(NSString*) value;
- (UserInfoBuilder*) clearNickName;

- (BOOL) hasSchoolName;
- (NSString*) schoolName;
- (UserInfoBuilder*) setSchoolName:(NSString*) value;
- (UserInfoBuilder*) clearSchoolName;

- (BOOL) hasPhone;
- (NSString*) phone;
- (UserInfoBuilder*) setPhone:(NSString*) value;
- (UserInfoBuilder*) clearPhone;

- (BOOL) hasExamType;
- (UInt32) examType;
- (UserInfoBuilder*) setExamType:(UInt32) value;
- (UserInfoBuilder*) clearExamType;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (UserInfoBuilder*) setChannelName:(NSString*) value;
- (UserInfoBuilder*) clearChannelName;
@end

#define RegisterResult_errorMessage @"errorMessage"
#define RegisterResult_userId @"userId"
#define RegisterResult_sessionId @"sessionId"
@interface RegisterResult : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasErrorMessage_:1;
  BOOL hasSessionId_:1;
  SInt32 userId;
  NSString* errorMessage;
  NSString* sessionId;
}
- (BOOL) hasErrorMessage;
- (BOOL) hasUserId;
- (BOOL) hasSessionId;
@property (readonly, strong) NSString* errorMessage;
@property (readonly) SInt32 userId;
@property (readonly, strong) NSString* sessionId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RegisterResultBuilder*) builder;
+ (RegisterResultBuilder*) builder;
+ (RegisterResultBuilder*) builderWithPrototype:(RegisterResult*) prototype;
- (RegisterResultBuilder*) toBuilder;

+ (RegisterResult*) parseFromData:(NSData*) data;
+ (RegisterResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterResult*) parseFromInputStream:(NSInputStream*) input;
+ (RegisterResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RegisterResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RegisterResultBuilder : PBGeneratedMessageBuilder {
@private
  RegisterResult* resultRegisterResult;
}

- (RegisterResult*) defaultInstance;

- (RegisterResultBuilder*) clear;
- (RegisterResultBuilder*) clone;

- (RegisterResult*) build;
- (RegisterResult*) buildPartial;

- (RegisterResultBuilder*) mergeFrom:(RegisterResult*) other;
- (RegisterResultBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RegisterResultBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (RegisterResultBuilder*) setErrorMessage:(NSString*) value;
- (RegisterResultBuilder*) clearErrorMessage;

- (BOOL) hasUserId;
- (SInt32) userId;
- (RegisterResultBuilder*) setUserId:(SInt32) value;
- (RegisterResultBuilder*) clearUserId;

- (BOOL) hasSessionId;
- (NSString*) sessionId;
- (RegisterResultBuilder*) setSessionId:(NSString*) value;
- (RegisterResultBuilder*) clearSessionId;
@end

#define Barrage_senderNickname @"senderNickname"
#define Barrage_message @"message"
@interface Barrage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSenderNickname_:1;
  BOOL hasMessage_:1;
  NSString* senderNickname;
  NSString* message;
}
- (BOOL) hasSenderNickname;
- (BOOL) hasMessage;
@property (readonly, strong) NSString* senderNickname;
@property (readonly, strong) NSString* message;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BarrageBuilder*) builder;
+ (BarrageBuilder*) builder;
+ (BarrageBuilder*) builderWithPrototype:(Barrage*) prototype;
- (BarrageBuilder*) toBuilder;

+ (Barrage*) parseFromData:(NSData*) data;
+ (Barrage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Barrage*) parseFromInputStream:(NSInputStream*) input;
+ (Barrage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Barrage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Barrage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BarrageBuilder : PBGeneratedMessageBuilder {
@private
  Barrage* resultBarrage;
}

- (Barrage*) defaultInstance;

- (BarrageBuilder*) clear;
- (BarrageBuilder*) clone;

- (Barrage*) build;
- (Barrage*) buildPartial;

- (BarrageBuilder*) mergeFrom:(Barrage*) other;
- (BarrageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BarrageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSenderNickname;
- (NSString*) senderNickname;
- (BarrageBuilder*) setSenderNickname:(NSString*) value;
- (BarrageBuilder*) clearSenderNickname;

- (BOOL) hasMessage;
- (NSString*) message;
- (BarrageBuilder*) setMessage:(NSString*) value;
- (BarrageBuilder*) clearMessage;
@end

@interface None : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NoneBuilder*) builder;
+ (NoneBuilder*) builder;
+ (NoneBuilder*) builderWithPrototype:(None*) prototype;
- (NoneBuilder*) toBuilder;

+ (None*) parseFromData:(NSData*) data;
+ (None*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (None*) parseFromInputStream:(NSInputStream*) input;
+ (None*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (None*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (None*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NoneBuilder : PBGeneratedMessageBuilder {
@private
  None* resultNone;
}

- (None*) defaultInstance;

- (NoneBuilder*) clear;
- (NoneBuilder*) clone;

- (None*) build;
- (None*) buildPartial;

- (NoneBuilder*) mergeFrom:(None*) other;
- (NoneBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NoneBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define ImportMessage_courseInfo @"courseInfo"
#define ImportMessage_courseList @"courseList"
@interface ImportMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCourseInfo_:1;
  BOOL hasCourseList_:1;
  CourseInfo* courseInfo;
  CourseList* courseList;
}
- (BOOL) hasCourseInfo;
- (BOOL) hasCourseList;
@property (readonly, strong) CourseInfo* courseInfo;
@property (readonly, strong) CourseList* courseList;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ImportMessageBuilder*) builder;
+ (ImportMessageBuilder*) builder;
+ (ImportMessageBuilder*) builderWithPrototype:(ImportMessage*) prototype;
- (ImportMessageBuilder*) toBuilder;

+ (ImportMessage*) parseFromData:(NSData*) data;
+ (ImportMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ImportMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ImportMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ImportMessageBuilder : PBGeneratedMessageBuilder {
@private
  ImportMessage* resultImportMessage;
}

- (ImportMessage*) defaultInstance;

- (ImportMessageBuilder*) clear;
- (ImportMessageBuilder*) clone;

- (ImportMessage*) build;
- (ImportMessage*) buildPartial;

- (ImportMessageBuilder*) mergeFrom:(ImportMessage*) other;
- (ImportMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ImportMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCourseInfo;
- (CourseInfo*) courseInfo;
- (ImportMessageBuilder*) setCourseInfo:(CourseInfo*) value;
- (ImportMessageBuilder*) setCourseInfoBuilder:(CourseInfoBuilder*) builderForValue;
- (ImportMessageBuilder*) mergeCourseInfo:(CourseInfo*) value;
- (ImportMessageBuilder*) clearCourseInfo;

- (BOOL) hasCourseList;
- (CourseList*) courseList;
- (ImportMessageBuilder*) setCourseList:(CourseList*) value;
- (ImportMessageBuilder*) setCourseListBuilder:(CourseListBuilder*) builderForValue;
- (ImportMessageBuilder*) mergeCourseList:(CourseList*) value;
- (ImportMessageBuilder*) clearCourseList;
@end


// @@protoc_insertion_point(global_scope)
