// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Barrage;
@class BarrageBuilder;
@class CourseInfo;
@class CourseInfoBuilder;
@class CourseList;
@class CourseListBuilder;
@class CourseType;
@class CourseTypeBuilder;
@class None;
@class NoneBuilder;
@class RegisterResult;
@class RegisterResultBuilder;
@class UserInfo;
@class UserInfoBuilder;



@interface YingshibaoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define UserInfo_nickName @"nickName"
#define UserInfo_schoolName @"schoolName"
#define UserInfo_phone @"phone"
#define UserInfo_examType @"examType"
#define UserInfo_channelName @"channelName"
@interface UserInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNickName_:1;
  BOOL hasSchoolName_:1;
  BOOL hasPhone_:1;
  BOOL hasChannelName_:1;
  BOOL hasExamType_:1;
  NSString* nickName;
  NSString* schoolName;
  NSString* phone;
  NSString* channelName;
  UInt32 examType;
}
- (BOOL) hasNickName;
- (BOOL) hasSchoolName;
- (BOOL) hasPhone;
- (BOOL) hasExamType;
- (BOOL) hasChannelName;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* schoolName;
@property (readonly, strong) NSString* phone;
@property (readonly) UInt32 examType;
@property (readonly, strong) NSString* channelName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserInfoBuilder*) builder;
+ (UserInfoBuilder*) builder;
+ (UserInfoBuilder*) builderWithPrototype:(UserInfo*) prototype;
- (UserInfoBuilder*) toBuilder;

+ (UserInfo*) parseFromData:(NSData*) data;
+ (UserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserInfoBuilder : PBGeneratedMessageBuilder {
@private
  UserInfo* resultUserInfo;
}

- (UserInfo*) defaultInstance;

- (UserInfoBuilder*) clear;
- (UserInfoBuilder*) clone;

- (UserInfo*) build;
- (UserInfo*) buildPartial;

- (UserInfoBuilder*) mergeFrom:(UserInfo*) other;
- (UserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (UserInfoBuilder*) setNickName:(NSString*) value;
- (UserInfoBuilder*) clearNickName;

- (BOOL) hasSchoolName;
- (NSString*) schoolName;
- (UserInfoBuilder*) setSchoolName:(NSString*) value;
- (UserInfoBuilder*) clearSchoolName;

- (BOOL) hasPhone;
- (NSString*) phone;
- (UserInfoBuilder*) setPhone:(NSString*) value;
- (UserInfoBuilder*) clearPhone;

- (BOOL) hasExamType;
- (UInt32) examType;
- (UserInfoBuilder*) setExamType:(UInt32) value;
- (UserInfoBuilder*) clearExamType;

- (BOOL) hasChannelName;
- (NSString*) channelName;
- (UserInfoBuilder*) setChannelName:(NSString*) value;
- (UserInfoBuilder*) clearChannelName;
@end

#define RegisterResult_errorMessage @"errorMessage"
#define RegisterResult_userId @"userId"
#define RegisterResult_sessionId @"sessionId"
@interface RegisterResult : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasErrorMessage_:1;
  BOOL hasSessionId_:1;
  SInt32 userId;
  NSString* errorMessage;
  NSString* sessionId;
}
- (BOOL) hasErrorMessage;
- (BOOL) hasUserId;
- (BOOL) hasSessionId;
@property (readonly, strong) NSString* errorMessage;
@property (readonly) SInt32 userId;
@property (readonly, strong) NSString* sessionId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RegisterResultBuilder*) builder;
+ (RegisterResultBuilder*) builder;
+ (RegisterResultBuilder*) builderWithPrototype:(RegisterResult*) prototype;
- (RegisterResultBuilder*) toBuilder;

+ (RegisterResult*) parseFromData:(NSData*) data;
+ (RegisterResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterResult*) parseFromInputStream:(NSInputStream*) input;
+ (RegisterResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RegisterResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RegisterResultBuilder : PBGeneratedMessageBuilder {
@private
  RegisterResult* resultRegisterResult;
}

- (RegisterResult*) defaultInstance;

- (RegisterResultBuilder*) clear;
- (RegisterResultBuilder*) clone;

- (RegisterResult*) build;
- (RegisterResult*) buildPartial;

- (RegisterResultBuilder*) mergeFrom:(RegisterResult*) other;
- (RegisterResultBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RegisterResultBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (RegisterResultBuilder*) setErrorMessage:(NSString*) value;
- (RegisterResultBuilder*) clearErrorMessage;

- (BOOL) hasUserId;
- (SInt32) userId;
- (RegisterResultBuilder*) setUserId:(SInt32) value;
- (RegisterResultBuilder*) clearUserId;

- (BOOL) hasSessionId;
- (NSString*) sessionId;
- (RegisterResultBuilder*) setSessionId:(NSString*) value;
- (RegisterResultBuilder*) clearSessionId;
@end

#define CourseType_courseType @"courseType"
#define CourseType_num @"num"
#define CourseType_pageNum @"pageNum"
@interface CourseType : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCourseType_:1;
  BOOL hasNum_:1;
  BOOL hasPageNum_:1;
  UInt32 courseType;
  UInt32 num;
  UInt32 pageNum;
}
- (BOOL) hasCourseType;
- (BOOL) hasNum;
- (BOOL) hasPageNum;
@property (readonly) UInt32 courseType;
@property (readonly) UInt32 num;
@property (readonly) UInt32 pageNum;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CourseTypeBuilder*) builder;
+ (CourseTypeBuilder*) builder;
+ (CourseTypeBuilder*) builderWithPrototype:(CourseType*) prototype;
- (CourseTypeBuilder*) toBuilder;

+ (CourseType*) parseFromData:(NSData*) data;
+ (CourseType*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CourseType*) parseFromInputStream:(NSInputStream*) input;
+ (CourseType*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CourseType*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CourseType*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CourseTypeBuilder : PBGeneratedMessageBuilder {
@private
  CourseType* resultCourseType;
}

- (CourseType*) defaultInstance;

- (CourseTypeBuilder*) clear;
- (CourseTypeBuilder*) clone;

- (CourseType*) build;
- (CourseType*) buildPartial;

- (CourseTypeBuilder*) mergeFrom:(CourseType*) other;
- (CourseTypeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CourseTypeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCourseType;
- (UInt32) courseType;
- (CourseTypeBuilder*) setCourseType:(UInt32) value;
- (CourseTypeBuilder*) clearCourseType;

- (BOOL) hasNum;
- (UInt32) num;
- (CourseTypeBuilder*) setNum:(UInt32) value;
- (CourseTypeBuilder*) clearNum;

- (BOOL) hasPageNum;
- (UInt32) pageNum;
- (CourseTypeBuilder*) setPageNum:(UInt32) value;
- (CourseTypeBuilder*) clearPageNum;
@end

#define CourseInfo_id @"id"
#define CourseInfo_name @"name"
#define CourseInfo_teacherName @"teacherName"
#define CourseInfo_price @"price"
#define CourseInfo_descritpion @"descritpion"
@interface CourseInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasPrice_:1;
  BOOL hasName_:1;
  BOOL hasTeacherName_:1;
  BOOL hasDescritpion_:1;
  SInt32 id;
  SInt32 price;
  NSString* name;
  NSString* teacherName;
  NSString* descritpion;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasTeacherName;
- (BOOL) hasPrice;
- (BOOL) hasDescritpion;
@property (readonly) SInt32 id;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* teacherName;
@property (readonly) SInt32 price;
@property (readonly, strong) NSString* descritpion;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CourseInfoBuilder*) builder;
+ (CourseInfoBuilder*) builder;
+ (CourseInfoBuilder*) builderWithPrototype:(CourseInfo*) prototype;
- (CourseInfoBuilder*) toBuilder;

+ (CourseInfo*) parseFromData:(NSData*) data;
+ (CourseInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CourseInfo*) parseFromInputStream:(NSInputStream*) input;
+ (CourseInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CourseInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CourseInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CourseInfoBuilder : PBGeneratedMessageBuilder {
@private
  CourseInfo* resultCourseInfo;
}

- (CourseInfo*) defaultInstance;

- (CourseInfoBuilder*) clear;
- (CourseInfoBuilder*) clone;

- (CourseInfo*) build;
- (CourseInfo*) buildPartial;

- (CourseInfoBuilder*) mergeFrom:(CourseInfo*) other;
- (CourseInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CourseInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt32) id;
- (CourseInfoBuilder*) setId:(SInt32) value;
- (CourseInfoBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (CourseInfoBuilder*) setName:(NSString*) value;
- (CourseInfoBuilder*) clearName;

- (BOOL) hasTeacherName;
- (NSString*) teacherName;
- (CourseInfoBuilder*) setTeacherName:(NSString*) value;
- (CourseInfoBuilder*) clearTeacherName;

- (BOOL) hasPrice;
- (SInt32) price;
- (CourseInfoBuilder*) setPrice:(SInt32) value;
- (CourseInfoBuilder*) clearPrice;

- (BOOL) hasDescritpion;
- (NSString*) descritpion;
- (CourseInfoBuilder*) setDescritpion:(NSString*) value;
- (CourseInfoBuilder*) clearDescritpion;
@end

#define CourseList_num @"num"
#define CourseList_list @"list"
@interface CourseList : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNum_:1;
  SInt32 num;
  NSMutableArray * listArray;
}
- (BOOL) hasNum;
@property (readonly) SInt32 num;
@property (readonly, strong) NSArray * list;
- (CourseInfo*)listAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CourseListBuilder*) builder;
+ (CourseListBuilder*) builder;
+ (CourseListBuilder*) builderWithPrototype:(CourseList*) prototype;
- (CourseListBuilder*) toBuilder;

+ (CourseList*) parseFromData:(NSData*) data;
+ (CourseList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CourseList*) parseFromInputStream:(NSInputStream*) input;
+ (CourseList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CourseList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CourseList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CourseListBuilder : PBGeneratedMessageBuilder {
@private
  CourseList* resultCourseList;
}

- (CourseList*) defaultInstance;

- (CourseListBuilder*) clear;
- (CourseListBuilder*) clone;

- (CourseList*) build;
- (CourseList*) buildPartial;

- (CourseListBuilder*) mergeFrom:(CourseList*) other;
- (CourseListBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CourseListBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNum;
- (SInt32) num;
- (CourseListBuilder*) setNum:(SInt32) value;
- (CourseListBuilder*) clearNum;

- (NSMutableArray *)list;
- (CourseInfo*)listAtIndex:(NSUInteger)index;
- (CourseListBuilder *)addList:(CourseInfo*)value;
- (CourseListBuilder *)setListArray:(NSArray *)array;
- (CourseListBuilder *)clearList;
@end

#define Barrage_senderNickname @"senderNickname"
#define Barrage_message @"message"
@interface Barrage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSenderNickname_:1;
  BOOL hasMessage_:1;
  NSString* senderNickname;
  NSString* message;
}
- (BOOL) hasSenderNickname;
- (BOOL) hasMessage;
@property (readonly, strong) NSString* senderNickname;
@property (readonly, strong) NSString* message;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BarrageBuilder*) builder;
+ (BarrageBuilder*) builder;
+ (BarrageBuilder*) builderWithPrototype:(Barrage*) prototype;
- (BarrageBuilder*) toBuilder;

+ (Barrage*) parseFromData:(NSData*) data;
+ (Barrage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Barrage*) parseFromInputStream:(NSInputStream*) input;
+ (Barrage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Barrage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Barrage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BarrageBuilder : PBGeneratedMessageBuilder {
@private
  Barrage* resultBarrage;
}

- (Barrage*) defaultInstance;

- (BarrageBuilder*) clear;
- (BarrageBuilder*) clone;

- (Barrage*) build;
- (Barrage*) buildPartial;

- (BarrageBuilder*) mergeFrom:(Barrage*) other;
- (BarrageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BarrageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSenderNickname;
- (NSString*) senderNickname;
- (BarrageBuilder*) setSenderNickname:(NSString*) value;
- (BarrageBuilder*) clearSenderNickname;

- (BOOL) hasMessage;
- (NSString*) message;
- (BarrageBuilder*) setMessage:(NSString*) value;
- (BarrageBuilder*) clearMessage;
@end

@interface None : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NoneBuilder*) builder;
+ (NoneBuilder*) builder;
+ (NoneBuilder*) builderWithPrototype:(None*) prototype;
- (NoneBuilder*) toBuilder;

+ (None*) parseFromData:(NSData*) data;
+ (None*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (None*) parseFromInputStream:(NSInputStream*) input;
+ (None*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (None*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (None*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NoneBuilder : PBGeneratedMessageBuilder {
@private
  None* resultNone;
}

- (None*) defaultInstance;

- (NoneBuilder*) clear;
- (NoneBuilder*) clone;

- (None*) build;
- (None*) buildPartial;

- (NoneBuilder*) mergeFrom:(None*) other;
- (NoneBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NoneBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end


// @@protoc_insertion_point(global_scope)
