// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

/**
 * Protobuf type {@code yingshibao.Barrage}
 *
 * <pre>
 * 弹幕消息
 * </pre>
 */
public final class Barrage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:yingshibao.Barrage)
    BarrageOrBuilder {
  // Use Barrage.newBuilder() to construct.
  private Barrage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Barrage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Barrage defaultInstance;
  public static Barrage getDefaultInstance() {
    return defaultInstance;
  }

  public Barrage getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Barrage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            senderNickname_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            message_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_Barrage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_Barrage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yingshibao.app.idl.Barrage.class, com.yingshibao.app.idl.Barrage.Builder.class);
  }

  public static com.google.protobuf.Parser<Barrage> PARSER =
      new com.google.protobuf.AbstractParser<Barrage>() {
    public Barrage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Barrage(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Barrage> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int SENDERNICKNAME_FIELD_NUMBER = 1;
  private java.lang.Object senderNickname_;
  /**
   * <code>required string senderNickname = 1;</code>
   *
   * <pre>
   * 发弹幕用户昵称
   * </pre>
   */
  public boolean hasSenderNickname() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string senderNickname = 1;</code>
   *
   * <pre>
   * 发弹幕用户昵称
   * </pre>
   */
  public java.lang.String getSenderNickname() {
    java.lang.Object ref = senderNickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        senderNickname_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string senderNickname = 1;</code>
   *
   * <pre>
   * 发弹幕用户昵称
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSenderNicknameBytes() {
    java.lang.Object ref = senderNickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderNickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private java.lang.Object message_;
  /**
   * <code>required string message = 2;</code>
   *
   * <pre>
   * 弹幕消息
   * </pre>
   */
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string message = 2;</code>
   *
   * <pre>
   * 弹幕消息
   * </pre>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string message = 2;</code>
   *
   * <pre>
   * 弹幕消息
   * </pre>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    senderNickname_ = "";
    message_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSenderNickname()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMessage()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getSenderNicknameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getMessageBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getSenderNicknameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getMessageBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yingshibao.app.idl.Barrage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.Barrage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yingshibao.app.idl.Barrage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.Barrage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yingshibao.app.idl.Barrage prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yingshibao.Barrage}
   *
   * <pre>
   * 弹幕消息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yingshibao.Barrage)
      com.yingshibao.app.idl.BarrageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_Barrage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_Barrage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yingshibao.app.idl.Barrage.class, com.yingshibao.app.idl.Barrage.Builder.class);
    }

    // Construct using com.yingshibao.app.idl.Barrage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      senderNickname_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_Barrage_descriptor;
    }

    public com.yingshibao.app.idl.Barrage getDefaultInstanceForType() {
      return com.yingshibao.app.idl.Barrage.getDefaultInstance();
    }

    public com.yingshibao.app.idl.Barrage build() {
      com.yingshibao.app.idl.Barrage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yingshibao.app.idl.Barrage buildPartial() {
      com.yingshibao.app.idl.Barrage result = new com.yingshibao.app.idl.Barrage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.senderNickname_ = senderNickname_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.message_ = message_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yingshibao.app.idl.Barrage) {
        return mergeFrom((com.yingshibao.app.idl.Barrage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yingshibao.app.idl.Barrage other) {
      if (other == com.yingshibao.app.idl.Barrage.getDefaultInstance()) return this;
      if (other.hasSenderNickname()) {
        bitField0_ |= 0x00000001;
        senderNickname_ = other.senderNickname_;
        onChanged();
      }
      if (other.hasMessage()) {
        bitField0_ |= 0x00000002;
        message_ = other.message_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSenderNickname()) {
        
        return false;
      }
      if (!hasMessage()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yingshibao.app.idl.Barrage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yingshibao.app.idl.Barrage) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object senderNickname_ = "";
    /**
     * <code>required string senderNickname = 1;</code>
     *
     * <pre>
     * 发弹幕用户昵称
     * </pre>
     */
    public boolean hasSenderNickname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string senderNickname = 1;</code>
     *
     * <pre>
     * 发弹幕用户昵称
     * </pre>
     */
    public java.lang.String getSenderNickname() {
      java.lang.Object ref = senderNickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderNickname_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string senderNickname = 1;</code>
     *
     * <pre>
     * 发弹幕用户昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSenderNicknameBytes() {
      java.lang.Object ref = senderNickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string senderNickname = 1;</code>
     *
     * <pre>
     * 发弹幕用户昵称
     * </pre>
     */
    public Builder setSenderNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      senderNickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string senderNickname = 1;</code>
     *
     * <pre>
     * 发弹幕用户昵称
     * </pre>
     */
    public Builder clearSenderNickname() {
      bitField0_ = (bitField0_ & ~0x00000001);
      senderNickname_ = getDefaultInstance().getSenderNickname();
      onChanged();
      return this;
    }
    /**
     * <code>required string senderNickname = 1;</code>
     *
     * <pre>
     * 发弹幕用户昵称
     * </pre>
     */
    public Builder setSenderNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      senderNickname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>required string message = 2;</code>
     *
     * <pre>
     * 弹幕消息
     * </pre>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string message = 2;</code>
     *
     * <pre>
     * 弹幕消息
     * </pre>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string message = 2;</code>
     *
     * <pre>
     * 弹幕消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string message = 2;</code>
     *
     * <pre>
     * 弹幕消息
     * </pre>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string message = 2;</code>
     *
     * <pre>
     * 弹幕消息
     * </pre>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>required string message = 2;</code>
     *
     * <pre>
     * 弹幕消息
     * </pre>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:yingshibao.Barrage)
  }

  static {
    defaultInstance = new Barrage(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:yingshibao.Barrage)
}

