// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yingshibao.app.idl;

@SuppressWarnings("hiding")
public final class CourseList extends
    com.google.protobuf.nano.MessageNano {

  private static volatile CourseList[] _emptyArray;
  public static CourseList[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new CourseList[0];
        }
      }
    }
    return _emptyArray;
  }

  // required int32 num = 1;
  public int num;

  // repeated .yingshibao.CourseInfo list = 2;
  public com.yingshibao.app.idl.CourseInfo[] list;

  public CourseList() {
    clear();
  }

  public CourseList clear() {
    num = 0;
    list = com.yingshibao.app.idl.CourseInfo.emptyArray();
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    output.writeInt32(1, this.num);
    if (this.list != null && this.list.length > 0) {
      for (int i = 0; i < this.list.length; i++) {
        com.yingshibao.app.idl.CourseInfo element = this.list[i];
        if (element != null) {
          output.writeMessage(2, element);
        }
      }
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(1, this.num);
    if (this.list != null && this.list.length > 0) {
      for (int i = 0; i < this.list.length; i++) {
        com.yingshibao.app.idl.CourseInfo element = this.list[i];
        if (element != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, element);
        }
      }
    }
    return size;
  }

  @Override
  public CourseList mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.num = input.readInt32();
          break;
        }
        case 18: {
          int arrayLength = com.google.protobuf.nano.WireFormatNano
              .getRepeatedFieldArrayLength(input, 18);
          int i = this.list == null ? 0 : this.list.length;
          com.yingshibao.app.idl.CourseInfo[] newArray =
              new com.yingshibao.app.idl.CourseInfo[i + arrayLength];
          if (i != 0) {
            java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
          }
          for (; i < newArray.length - 1; i++) {
            newArray[i] = new com.yingshibao.app.idl.CourseInfo();
            input.readMessage(newArray[i]);
            input.readTag();
          }
          // Last one without readTag.
          newArray[i] = new com.yingshibao.app.idl.CourseInfo();
          input.readMessage(newArray[i]);
          this.list = newArray;
          break;
        }
      }
    }
  }

  public static CourseList parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new CourseList(), data);
  }

  public static CourseList parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new CourseList().mergeFrom(input);
  }
}
