// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.yingshibao.app.idl;

public interface CourseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yingshibao.CourseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   *
   * <pre>
   * 课程ID
   * </pre>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   *
   * <pre>
   * 课程ID
   * </pre>
   */
  int getId();

  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   * 课程名称
   * </pre>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   * 课程名称
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   *
   * <pre>
   * 课程名称
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string teacherName = 3;</code>
   *
   * <pre>
   * 老师姓名
   * </pre>
   */
  boolean hasTeacherName();
  /**
   * <code>required string teacherName = 3;</code>
   *
   * <pre>
   * 老师姓名
   * </pre>
   */
  java.lang.String getTeacherName();
  /**
   * <code>required string teacherName = 3;</code>
   *
   * <pre>
   * 老师姓名
   * </pre>
   */
  com.google.protobuf.ByteString
      getTeacherNameBytes();

  /**
   * <code>required int32 price = 4;</code>
   *
   * <pre>
   * 课程价格, 0:免费; 其他金额为课程价格，以分为单位。
   * </pre>
   */
  boolean hasPrice();
  /**
   * <code>required int32 price = 4;</code>
   *
   * <pre>
   * 课程价格, 0:免费; 其他金额为课程价格，以分为单位。
   * </pre>
   */
  int getPrice();

  /**
   * <code>required string descritpion = 5;</code>
   *
   * <pre>
   * 课程简介
   * </pre>
   */
  boolean hasDescritpion();
  /**
   * <code>required string descritpion = 5;</code>
   *
   * <pre>
   * 课程简介
   * </pre>
   */
  java.lang.String getDescritpion();
  /**
   * <code>required string descritpion = 5;</code>
   *
   * <pre>
   * 课程简介
   * </pre>
   */
  com.google.protobuf.ByteString
      getDescritpionBytes();
}
