// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yingshibao.app.idl;

@SuppressWarnings("hiding")
public final class CourseInfo extends
    com.google.protobuf.nano.MessageNano {

  private static volatile CourseInfo[] _emptyArray;
  public static CourseInfo[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new CourseInfo[0];
        }
      }
    }
    return _emptyArray;
  }

  // required int32 id = 1;
  public int id;

  // required string name = 2;
  public java.lang.String name;

  // required string teacherName = 3;
  public java.lang.String teacherName;

  // required int32 price = 4;
  public int price;

  // required string descritpion = 5;
  public java.lang.String descritpion;

  public CourseInfo() {
    clear();
  }

  public CourseInfo clear() {
    id = 0;
    name = "";
    teacherName = "";
    price = 0;
    descritpion = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    output.writeInt32(1, this.id);
    output.writeString(2, this.name);
    output.writeString(3, this.teacherName);
    output.writeInt32(4, this.price);
    output.writeString(5, this.descritpion);
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(1, this.id);
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeStringSize(2, this.name);
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeStringSize(3, this.teacherName);
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(4, this.price);
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeStringSize(5, this.descritpion);
    return size;
  }

  @Override
  public CourseInfo mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.id = input.readInt32();
          break;
        }
        case 18: {
          this.name = input.readString();
          break;
        }
        case 26: {
          this.teacherName = input.readString();
          break;
        }
        case 32: {
          this.price = input.readInt32();
          break;
        }
        case 42: {
          this.descritpion = input.readString();
          break;
        }
      }
    }
  }

  public static CourseInfo parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new CourseInfo(), data);
  }

  public static CourseInfo parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new CourseInfo().mergeFrom(input);
  }
}
