// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yingshibao.app.idl;

@SuppressWarnings("hiding")
public final class CourseType extends
    com.google.protobuf.nano.MessageNano {

  private static volatile CourseType[] _emptyArray;
  public static CourseType[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new CourseType[0];
        }
      }
    }
    return _emptyArray;
  }

  // required uint32 courseType = 1;
  public int courseType;

  // required uint32 num = 2;
  public int num;

  // required uint32 pageNum = 3;
  public int pageNum;

  public CourseType() {
    clear();
  }

  public CourseType clear() {
    courseType = 0;
    num = 0;
    pageNum = 0;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    output.writeUInt32(1, this.courseType);
    output.writeUInt32(2, this.num);
    output.writeUInt32(3, this.pageNum);
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeUInt32Size(1, this.courseType);
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeUInt32Size(2, this.num);
    size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeUInt32Size(3, this.pageNum);
    return size;
  }

  @Override
  public CourseType mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.courseType = input.readUInt32();
          break;
        }
        case 16: {
          this.num = input.readUInt32();
          break;
        }
        case 24: {
          this.pageNum = input.readUInt32();
          break;
        }
      }
    }
  }

  public static CourseType parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new CourseType(), data);
  }

  public static CourseType parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new CourseType().mergeFrom(input);
  }
}
