// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.yingshibao.app.idl;

/**
 * Protobuf type {@code yingshibao.CourseType}
 *
 * <pre>
 * 课程类型
 * </pre>
 */
public final class CourseType extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:yingshibao.CourseType)
    CourseTypeOrBuilder {
  // Use CourseType.newBuilder() to construct.
  private CourseType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CourseType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CourseType defaultInstance;
  public static CourseType getDefaultInstance() {
    return defaultInstance;
  }

  public CourseType getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CourseType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            courseType_ = input.readUInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            num_ = input.readUInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            pageNum_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yingshibao.app.idl.Module.internal_static_yingshibao_CourseType_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yingshibao.app.idl.Module.internal_static_yingshibao_CourseType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yingshibao.app.idl.CourseType.class, com.yingshibao.app.idl.CourseType.Builder.class);
  }

  public static com.google.protobuf.Parser<CourseType> PARSER =
      new com.google.protobuf.AbstractParser<CourseType>() {
    public CourseType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CourseType(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CourseType> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int COURSETYPE_FIELD_NUMBER = 1;
  private int courseType_;
  /**
   * <code>required uint32 courseType = 1;</code>
   *
   * <pre>
   * 课程类型 1:我的课程（已报名、已订购); 2:全部课程
   * </pre>
   */
  public boolean hasCourseType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required uint32 courseType = 1;</code>
   *
   * <pre>
   * 课程类型 1:我的课程（已报名、已订购); 2:全部课程
   * </pre>
   */
  public int getCourseType() {
    return courseType_;
  }

  public static final int NUM_FIELD_NUMBER = 2;
  private int num_;
  /**
   * <code>required uint32 num = 2;</code>
   *
   * <pre>
   * 指定返回列表中最大课程个数
   * </pre>
   */
  public boolean hasNum() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required uint32 num = 2;</code>
   *
   * <pre>
   * 指定返回列表中最大课程个数
   * </pre>
   */
  public int getNum() {
    return num_;
  }

  public static final int PAGENUM_FIELD_NUMBER = 3;
  private int pageNum_;
  /**
   * <code>required uint32 pageNum = 3;</code>
   *
   * <pre>
   * 指定返回第几页
   * </pre>
   */
  public boolean hasPageNum() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required uint32 pageNum = 3;</code>
   *
   * <pre>
   * 指定返回第几页
   * </pre>
   */
  public int getPageNum() {
    return pageNum_;
  }

  private void initFields() {
    courseType_ = 0;
    num_ = 0;
    pageNum_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasCourseType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasNum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPageNum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt32(1, courseType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt32(2, num_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeUInt32(3, pageNum_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, courseType_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, num_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, pageNum_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yingshibao.app.idl.CourseType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yingshibao.app.idl.CourseType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.CourseType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yingshibao.app.idl.CourseType prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yingshibao.CourseType}
   *
   * <pre>
   * 课程类型
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yingshibao.CourseType)
      com.yingshibao.app.idl.CourseTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yingshibao.app.idl.Module.internal_static_yingshibao_CourseType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yingshibao.app.idl.Module.internal_static_yingshibao_CourseType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yingshibao.app.idl.CourseType.class, com.yingshibao.app.idl.CourseType.Builder.class);
    }

    // Construct using com.yingshibao.app.idl.CourseType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      courseType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      num_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      pageNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yingshibao.app.idl.Module.internal_static_yingshibao_CourseType_descriptor;
    }

    public com.yingshibao.app.idl.CourseType getDefaultInstanceForType() {
      return com.yingshibao.app.idl.CourseType.getDefaultInstance();
    }

    public com.yingshibao.app.idl.CourseType build() {
      com.yingshibao.app.idl.CourseType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yingshibao.app.idl.CourseType buildPartial() {
      com.yingshibao.app.idl.CourseType result = new com.yingshibao.app.idl.CourseType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.courseType_ = courseType_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.num_ = num_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.pageNum_ = pageNum_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yingshibao.app.idl.CourseType) {
        return mergeFrom((com.yingshibao.app.idl.CourseType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yingshibao.app.idl.CourseType other) {
      if (other == com.yingshibao.app.idl.CourseType.getDefaultInstance()) return this;
      if (other.hasCourseType()) {
        setCourseType(other.getCourseType());
      }
      if (other.hasNum()) {
        setNum(other.getNum());
      }
      if (other.hasPageNum()) {
        setPageNum(other.getPageNum());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasCourseType()) {
        
        return false;
      }
      if (!hasNum()) {
        
        return false;
      }
      if (!hasPageNum()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yingshibao.app.idl.CourseType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yingshibao.app.idl.CourseType) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int courseType_ ;
    /**
     * <code>required uint32 courseType = 1;</code>
     *
     * <pre>
     * 课程类型 1:我的课程（已报名、已订购); 2:全部课程
     * </pre>
     */
    public boolean hasCourseType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 courseType = 1;</code>
     *
     * <pre>
     * 课程类型 1:我的课程（已报名、已订购); 2:全部课程
     * </pre>
     */
    public int getCourseType() {
      return courseType_;
    }
    /**
     * <code>required uint32 courseType = 1;</code>
     *
     * <pre>
     * 课程类型 1:我的课程（已报名、已订购); 2:全部课程
     * </pre>
     */
    public Builder setCourseType(int value) {
      bitField0_ |= 0x00000001;
      courseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 courseType = 1;</code>
     *
     * <pre>
     * 课程类型 1:我的课程（已报名、已订购); 2:全部课程
     * </pre>
     */
    public Builder clearCourseType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      courseType_ = 0;
      onChanged();
      return this;
    }

    private int num_ ;
    /**
     * <code>required uint32 num = 2;</code>
     *
     * <pre>
     * 指定返回列表中最大课程个数
     * </pre>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 num = 2;</code>
     *
     * <pre>
     * 指定返回列表中最大课程个数
     * </pre>
     */
    public int getNum() {
      return num_;
    }
    /**
     * <code>required uint32 num = 2;</code>
     *
     * <pre>
     * 指定返回列表中最大课程个数
     * </pre>
     */
    public Builder setNum(int value) {
      bitField0_ |= 0x00000002;
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 num = 2;</code>
     *
     * <pre>
     * 指定返回列表中最大课程个数
     * </pre>
     */
    public Builder clearNum() {
      bitField0_ = (bitField0_ & ~0x00000002);
      num_ = 0;
      onChanged();
      return this;
    }

    private int pageNum_ ;
    /**
     * <code>required uint32 pageNum = 3;</code>
     *
     * <pre>
     * 指定返回第几页
     * </pre>
     */
    public boolean hasPageNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 pageNum = 3;</code>
     *
     * <pre>
     * 指定返回第几页
     * </pre>
     */
    public int getPageNum() {
      return pageNum_;
    }
    /**
     * <code>required uint32 pageNum = 3;</code>
     *
     * <pre>
     * 指定返回第几页
     * </pre>
     */
    public Builder setPageNum(int value) {
      bitField0_ |= 0x00000004;
      pageNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 pageNum = 3;</code>
     *
     * <pre>
     * 指定返回第几页
     * </pre>
     */
    public Builder clearPageNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageNum_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:yingshibao.CourseType)
  }

  static {
    defaultInstance = new CourseType(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:yingshibao.CourseType)
}

