// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

/**
 * Protobuf type {@code yingshibao.ImportMessage}
 *
 * <pre>
 * 引用import的message
 * </pre>
 */
public final class ImportMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:yingshibao.ImportMessage)
    ImportMessageOrBuilder {
  // Use ImportMessage.newBuilder() to construct.
  private ImportMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ImportMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ImportMessage defaultInstance;
  public static ImportMessage getDefaultInstance() {
    return defaultInstance;
  }

  public ImportMessage getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ImportMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.yingshibao.app.idl.CourseInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = courseInfo_.toBuilder();
            }
            courseInfo_ = input.readMessage(com.yingshibao.app.idl.CourseInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(courseInfo_);
              courseInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.yingshibao.app.idl.CourseList.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = courseList_.toBuilder();
            }
            courseList_ = input.readMessage(com.yingshibao.app.idl.CourseList.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(courseList_);
              courseList_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_ImportMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_ImportMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yingshibao.app.idl.ImportMessage.class, com.yingshibao.app.idl.ImportMessage.Builder.class);
  }

  public static com.google.protobuf.Parser<ImportMessage> PARSER =
      new com.google.protobuf.AbstractParser<ImportMessage>() {
    public ImportMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImportMessage(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ImportMessage> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int COURSEINFO_FIELD_NUMBER = 1;
  private com.yingshibao.app.idl.CourseInfo courseInfo_;
  /**
   * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
   */
  public boolean hasCourseInfo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
   */
  public com.yingshibao.app.idl.CourseInfo getCourseInfo() {
    return courseInfo_;
  }
  /**
   * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
   */
  public com.yingshibao.app.idl.CourseInfoOrBuilder getCourseInfoOrBuilder() {
    return courseInfo_;
  }

  public static final int COURSELIST_FIELD_NUMBER = 2;
  private com.yingshibao.app.idl.CourseList courseList_;
  /**
   * <code>optional .yingshibao.CourseList courseList = 2;</code>
   */
  public boolean hasCourseList() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .yingshibao.CourseList courseList = 2;</code>
   */
  public com.yingshibao.app.idl.CourseList getCourseList() {
    return courseList_;
  }
  /**
   * <code>optional .yingshibao.CourseList courseList = 2;</code>
   */
  public com.yingshibao.app.idl.CourseListOrBuilder getCourseListOrBuilder() {
    return courseList_;
  }

  private void initFields() {
    courseInfo_ = com.yingshibao.app.idl.CourseInfo.getDefaultInstance();
    courseList_ = com.yingshibao.app.idl.CourseList.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasCourseInfo()) {
      if (!getCourseInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasCourseList()) {
      if (!getCourseList().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, courseInfo_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, courseList_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, courseInfo_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, courseList_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yingshibao.app.idl.ImportMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.ImportMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yingshibao.app.idl.ImportMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.ImportMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yingshibao.app.idl.ImportMessage prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yingshibao.ImportMessage}
   *
   * <pre>
   * 引用import的message
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yingshibao.ImportMessage)
      com.yingshibao.app.idl.ImportMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_ImportMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_ImportMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yingshibao.app.idl.ImportMessage.class, com.yingshibao.app.idl.ImportMessage.Builder.class);
    }

    // Construct using com.yingshibao.app.idl.ImportMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getCourseInfoFieldBuilder();
        getCourseListFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (courseInfoBuilder_ == null) {
        courseInfo_ = com.yingshibao.app.idl.CourseInfo.getDefaultInstance();
      } else {
        courseInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (courseListBuilder_ == null) {
        courseList_ = com.yingshibao.app.idl.CourseList.getDefaultInstance();
      } else {
        courseListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_ImportMessage_descriptor;
    }

    public com.yingshibao.app.idl.ImportMessage getDefaultInstanceForType() {
      return com.yingshibao.app.idl.ImportMessage.getDefaultInstance();
    }

    public com.yingshibao.app.idl.ImportMessage build() {
      com.yingshibao.app.idl.ImportMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yingshibao.app.idl.ImportMessage buildPartial() {
      com.yingshibao.app.idl.ImportMessage result = new com.yingshibao.app.idl.ImportMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (courseInfoBuilder_ == null) {
        result.courseInfo_ = courseInfo_;
      } else {
        result.courseInfo_ = courseInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (courseListBuilder_ == null) {
        result.courseList_ = courseList_;
      } else {
        result.courseList_ = courseListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yingshibao.app.idl.ImportMessage) {
        return mergeFrom((com.yingshibao.app.idl.ImportMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yingshibao.app.idl.ImportMessage other) {
      if (other == com.yingshibao.app.idl.ImportMessage.getDefaultInstance()) return this;
      if (other.hasCourseInfo()) {
        mergeCourseInfo(other.getCourseInfo());
      }
      if (other.hasCourseList()) {
        mergeCourseList(other.getCourseList());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (hasCourseInfo()) {
        if (!getCourseInfo().isInitialized()) {
          
          return false;
        }
      }
      if (hasCourseList()) {
        if (!getCourseList().isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yingshibao.app.idl.ImportMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yingshibao.app.idl.ImportMessage) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.yingshibao.app.idl.CourseInfo courseInfo_ = com.yingshibao.app.idl.CourseInfo.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.yingshibao.app.idl.CourseInfo, com.yingshibao.app.idl.CourseInfo.Builder, com.yingshibao.app.idl.CourseInfoOrBuilder> courseInfoBuilder_;
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public boolean hasCourseInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public com.yingshibao.app.idl.CourseInfo getCourseInfo() {
      if (courseInfoBuilder_ == null) {
        return courseInfo_;
      } else {
        return courseInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public Builder setCourseInfo(com.yingshibao.app.idl.CourseInfo value) {
      if (courseInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        courseInfo_ = value;
        onChanged();
      } else {
        courseInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public Builder setCourseInfo(
        com.yingshibao.app.idl.CourseInfo.Builder builderForValue) {
      if (courseInfoBuilder_ == null) {
        courseInfo_ = builderForValue.build();
        onChanged();
      } else {
        courseInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public Builder mergeCourseInfo(com.yingshibao.app.idl.CourseInfo value) {
      if (courseInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            courseInfo_ != com.yingshibao.app.idl.CourseInfo.getDefaultInstance()) {
          courseInfo_ =
            com.yingshibao.app.idl.CourseInfo.newBuilder(courseInfo_).mergeFrom(value).buildPartial();
        } else {
          courseInfo_ = value;
        }
        onChanged();
      } else {
        courseInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public Builder clearCourseInfo() {
      if (courseInfoBuilder_ == null) {
        courseInfo_ = com.yingshibao.app.idl.CourseInfo.getDefaultInstance();
        onChanged();
      } else {
        courseInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public com.yingshibao.app.idl.CourseInfo.Builder getCourseInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCourseInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    public com.yingshibao.app.idl.CourseInfoOrBuilder getCourseInfoOrBuilder() {
      if (courseInfoBuilder_ != null) {
        return courseInfoBuilder_.getMessageOrBuilder();
      } else {
        return courseInfo_;
      }
    }
    /**
     * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.yingshibao.app.idl.CourseInfo, com.yingshibao.app.idl.CourseInfo.Builder, com.yingshibao.app.idl.CourseInfoOrBuilder> 
        getCourseInfoFieldBuilder() {
      if (courseInfoBuilder_ == null) {
        courseInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.yingshibao.app.idl.CourseInfo, com.yingshibao.app.idl.CourseInfo.Builder, com.yingshibao.app.idl.CourseInfoOrBuilder>(
                getCourseInfo(),
                getParentForChildren(),
                isClean());
        courseInfo_ = null;
      }
      return courseInfoBuilder_;
    }

    private com.yingshibao.app.idl.CourseList courseList_ = com.yingshibao.app.idl.CourseList.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.yingshibao.app.idl.CourseList, com.yingshibao.app.idl.CourseList.Builder, com.yingshibao.app.idl.CourseListOrBuilder> courseListBuilder_;
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public boolean hasCourseList() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public com.yingshibao.app.idl.CourseList getCourseList() {
      if (courseListBuilder_ == null) {
        return courseList_;
      } else {
        return courseListBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public Builder setCourseList(com.yingshibao.app.idl.CourseList value) {
      if (courseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        courseList_ = value;
        onChanged();
      } else {
        courseListBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public Builder setCourseList(
        com.yingshibao.app.idl.CourseList.Builder builderForValue) {
      if (courseListBuilder_ == null) {
        courseList_ = builderForValue.build();
        onChanged();
      } else {
        courseListBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public Builder mergeCourseList(com.yingshibao.app.idl.CourseList value) {
      if (courseListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            courseList_ != com.yingshibao.app.idl.CourseList.getDefaultInstance()) {
          courseList_ =
            com.yingshibao.app.idl.CourseList.newBuilder(courseList_).mergeFrom(value).buildPartial();
        } else {
          courseList_ = value;
        }
        onChanged();
      } else {
        courseListBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public Builder clearCourseList() {
      if (courseListBuilder_ == null) {
        courseList_ = com.yingshibao.app.idl.CourseList.getDefaultInstance();
        onChanged();
      } else {
        courseListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public com.yingshibao.app.idl.CourseList.Builder getCourseListBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCourseListFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    public com.yingshibao.app.idl.CourseListOrBuilder getCourseListOrBuilder() {
      if (courseListBuilder_ != null) {
        return courseListBuilder_.getMessageOrBuilder();
      } else {
        return courseList_;
      }
    }
    /**
     * <code>optional .yingshibao.CourseList courseList = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.yingshibao.app.idl.CourseList, com.yingshibao.app.idl.CourseList.Builder, com.yingshibao.app.idl.CourseListOrBuilder> 
        getCourseListFieldBuilder() {
      if (courseListBuilder_ == null) {
        courseListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.yingshibao.app.idl.CourseList, com.yingshibao.app.idl.CourseList.Builder, com.yingshibao.app.idl.CourseListOrBuilder>(
                getCourseList(),
                getParentForChildren(),
                isClean());
        courseList_ = null;
      }
      return courseListBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:yingshibao.ImportMessage)
  }

  static {
    defaultInstance = new ImportMessage(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:yingshibao.ImportMessage)
}

