// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

public interface NoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yingshibao.None)
    com.google.protobuf.MessageOrBuilder {
}
