// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

public interface RegisterResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yingshibao.RegisterResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string errorMessage = 1;</code>
   *
   * <pre>
   * 错误信息，如果注册成功为null；如果发生错误，存放导致错误的原因。
   * </pre>
   */
  boolean hasErrorMessage();
  /**
   * <code>required string errorMessage = 1;</code>
   *
   * <pre>
   * 错误信息，如果注册成功为null；如果发生错误，存放导致错误的原因。
   * </pre>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>required string errorMessage = 1;</code>
   *
   * <pre>
   * 错误信息，如果注册成功为null；如果发生错误，存放导致错误的原因。
   * </pre>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>optional int32 userId = 2;</code>
   *
   * <pre>
   * 用户ID，注册成功时存放服务器生成的userId。
   * </pre>
   */
  boolean hasUserId();
  /**
   * <code>optional int32 userId = 2;</code>
   *
   * <pre>
   * 用户ID，注册成功时存放服务器生成的userId。
   * </pre>
   */
  int getUserId();

  /**
   * <code>optional string sessionId = 3;</code>
   *
   * <pre>
   * sessionId，注册成功时自动登录了，存放服务器生成的sessionId。
   * </pre>
   */
  boolean hasSessionId();
  /**
   * <code>optional string sessionId = 3;</code>
   *
   * <pre>
   * sessionId，注册成功时自动登录了，存放服务器生成的sessionId。
   * </pre>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string sessionId = 3;</code>
   *
   * <pre>
   * sessionId，注册成功时自动登录了，存放服务器生成的sessionId。
   * </pre>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
