// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

public final class Yingshibao {
  private Yingshibao() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_UserInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_RegisterResult_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_RegisterResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_Barrage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_Barrage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_None_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_None_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_ImportMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_ImportMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020yingshibao.proto\022\nyingshibao\032\014module.p" +
      "roto\"f\n\010UserInfo\022\020\n\010nickName\030\001 \002(\t\022\022\n\nsc" +
      "hoolName\030\002 \001(\t\022\r\n\005phone\030\003 \002(\t\022\020\n\010examTyp" +
      "e\030\004 \002(\r\022\023\n\013channelName\030\005 \002(\t\"I\n\016Register" +
      "Result\022\024\n\014errorMessage\030\001 \002(\t\022\016\n\006userId\030\002" +
      " \001(\005\022\021\n\tsessionId\030\003 \001(\t\"2\n\007Barrage\022\026\n\016se" +
      "nderNickname\030\001 \002(\t\022\017\n\007message\030\002 \002(\t\"\006\n\004N" +
      "one\"g\n\rImportMessage\022*\n\ncourseInfo\030\001 \001(\013" +
      "2\026.yingshibao.CourseInfo\022*\n\ncourseList\030\002" +
      " \001(\0132\026.yingshibao.CourseList2T\n\013UserMana",
      "ger\022E\n\017registerNewUser\022\024.yingshibao.User" +
      "Info\032\032.yingshibao.RegisterResult\"\0002>\n\004Pu" +
      "sh\0226\n\013pushBarrage\022\023.yingshibao.Barrage\032\020" +
      ".yingshibao.None\"\0002R\n\rCourseManager\022A\n\rg" +
      "etCourseList\022\026.yingshibao.CourseType\032\026.y" +
      "ingshibao.CourseList\"\000B\032\n\026com.yingshibao" +
      ".app.idlP\001P\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yingshibao.app.idl.Module.getDescriptor(),
        }, assigner);
    internal_static_yingshibao_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yingshibao_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_UserInfo_descriptor,
        new java.lang.String[] { "NickName", "SchoolName", "Phone", "ExamType", "ChannelName", });
    internal_static_yingshibao_RegisterResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yingshibao_RegisterResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_RegisterResult_descriptor,
        new java.lang.String[] { "ErrorMessage", "UserId", "SessionId", });
    internal_static_yingshibao_Barrage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_yingshibao_Barrage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_Barrage_descriptor,
        new java.lang.String[] { "SenderNickname", "Message", });
    internal_static_yingshibao_None_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_yingshibao_None_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_None_descriptor,
        new java.lang.String[] { });
    internal_static_yingshibao_ImportMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_yingshibao_ImportMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_ImportMessage_descriptor,
        new java.lang.String[] { "CourseInfo", "CourseList", });
    com.yingshibao.app.idl.Module.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
