// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

public interface CourseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yingshibao.CourseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 num = 1;</code>
   *
   * <pre>
   * 列表实际条数
   * </pre>
   */
  boolean hasNum();
  /**
   * <code>required int32 num = 1;</code>
   *
   * <pre>
   * 列表实际条数
   * </pre>
   */
  int getNum();

  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  java.util.List<com.yingshibao.app.idl.CourseInfo> 
      getListList();
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  com.yingshibao.app.idl.CourseInfo getList(int index);
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  int getListCount();
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  java.util.List<? extends com.yingshibao.app.idl.CourseInfoOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  com.yingshibao.app.idl.CourseInfoOrBuilder getListOrBuilder(
      int index);
}
