// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

/**
 * Protobuf type {@code yingshibao.CourseList}
 *
 * <pre>
 * 课程列表
 * </pre>
 */
public final class CourseList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:yingshibao.CourseList)
    CourseListOrBuilder {
  // Use CourseList.newBuilder() to construct.
  private CourseList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CourseList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CourseList defaultInstance;
  public static CourseList getDefaultInstance() {
    return defaultInstance;
  }

  public CourseList getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CourseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            num_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              list_ = new java.util.ArrayList<com.yingshibao.app.idl.CourseInfo>();
              mutable_bitField0_ |= 0x00000002;
            }
            list_.add(input.readMessage(com.yingshibao.app.idl.CourseInfo.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        list_ = java.util.Collections.unmodifiableList(list_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_CourseList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_CourseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yingshibao.app.idl.CourseList.class, com.yingshibao.app.idl.CourseList.Builder.class);
  }

  public static com.google.protobuf.Parser<CourseList> PARSER =
      new com.google.protobuf.AbstractParser<CourseList>() {
    public CourseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CourseList(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CourseList> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NUM_FIELD_NUMBER = 1;
  private int num_;
  /**
   * <code>required int32 num = 1;</code>
   *
   * <pre>
   * 列表实际条数
   * </pre>
   */
  public boolean hasNum() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 num = 1;</code>
   *
   * <pre>
   * 列表实际条数
   * </pre>
   */
  public int getNum() {
    return num_;
  }

  public static final int LIST_FIELD_NUMBER = 2;
  private java.util.List<com.yingshibao.app.idl.CourseInfo> list_;
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  public java.util.List<com.yingshibao.app.idl.CourseInfo> getListList() {
    return list_;
  }
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  public java.util.List<? extends com.yingshibao.app.idl.CourseInfoOrBuilder> 
      getListOrBuilderList() {
    return list_;
  }
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  public int getListCount() {
    return list_.size();
  }
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  public com.yingshibao.app.idl.CourseInfo getList(int index) {
    return list_.get(index);
  }
  /**
   * <code>repeated .yingshibao.CourseInfo list = 2;</code>
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  public com.yingshibao.app.idl.CourseInfoOrBuilder getListOrBuilder(
      int index) {
    return list_.get(index);
  }

  private void initFields() {
    num_ = 0;
    list_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasNum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getListCount(); i++) {
      if (!getList(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, num_);
    }
    for (int i = 0; i < list_.size(); i++) {
      output.writeMessage(2, list_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, num_);
    }
    for (int i = 0; i < list_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, list_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yingshibao.app.idl.CourseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yingshibao.app.idl.CourseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.CourseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yingshibao.app.idl.CourseList prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yingshibao.CourseList}
   *
   * <pre>
   * 课程列表
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yingshibao.CourseList)
      com.yingshibao.app.idl.CourseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_CourseList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_CourseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yingshibao.app.idl.CourseList.class, com.yingshibao.app.idl.CourseList.Builder.class);
    }

    // Construct using com.yingshibao.app.idl.CourseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getListFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      num_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (listBuilder_ == null) {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        listBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_CourseList_descriptor;
    }

    public com.yingshibao.app.idl.CourseList getDefaultInstanceForType() {
      return com.yingshibao.app.idl.CourseList.getDefaultInstance();
    }

    public com.yingshibao.app.idl.CourseList build() {
      com.yingshibao.app.idl.CourseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yingshibao.app.idl.CourseList buildPartial() {
      com.yingshibao.app.idl.CourseList result = new com.yingshibao.app.idl.CourseList(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.num_ = num_;
      if (listBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          list_ = java.util.Collections.unmodifiableList(list_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.list_ = list_;
      } else {
        result.list_ = listBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yingshibao.app.idl.CourseList) {
        return mergeFrom((com.yingshibao.app.idl.CourseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yingshibao.app.idl.CourseList other) {
      if (other == com.yingshibao.app.idl.CourseList.getDefaultInstance()) return this;
      if (other.hasNum()) {
        setNum(other.getNum());
      }
      if (listBuilder_ == null) {
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
      } else {
        if (!other.list_.isEmpty()) {
          if (listBuilder_.isEmpty()) {
            listBuilder_.dispose();
            listBuilder_ = null;
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000002);
            listBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getListFieldBuilder() : null;
          } else {
            listBuilder_.addAllMessages(other.list_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasNum()) {
        
        return false;
      }
      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yingshibao.app.idl.CourseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yingshibao.app.idl.CourseList) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int num_ ;
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     * 列表实际条数
     * </pre>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     * 列表实际条数
     * </pre>
     */
    public int getNum() {
      return num_;
    }
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     * 列表实际条数
     * </pre>
     */
    public Builder setNum(int value) {
      bitField0_ |= 0x00000001;
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     * 列表实际条数
     * </pre>
     */
    public Builder clearNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      num_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.yingshibao.app.idl.CourseInfo> list_ =
      java.util.Collections.emptyList();
    private void ensureListIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        list_ = new java.util.ArrayList<com.yingshibao.app.idl.CourseInfo>(list_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.yingshibao.app.idl.CourseInfo, com.yingshibao.app.idl.CourseInfo.Builder, com.yingshibao.app.idl.CourseInfoOrBuilder> listBuilder_;

    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public java.util.List<com.yingshibao.app.idl.CourseInfo> getListList() {
      if (listBuilder_ == null) {
        return java.util.Collections.unmodifiableList(list_);
      } else {
        return listBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public int getListCount() {
      if (listBuilder_ == null) {
        return list_.size();
      } else {
        return listBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public com.yingshibao.app.idl.CourseInfo getList(int index) {
      if (listBuilder_ == null) {
        return list_.get(index);
      } else {
        return listBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder setList(
        int index, com.yingshibao.app.idl.CourseInfo value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.set(index, value);
        onChanged();
      } else {
        listBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder setList(
        int index, com.yingshibao.app.idl.CourseInfo.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.set(index, builderForValue.build());
        onChanged();
      } else {
        listBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder addList(com.yingshibao.app.idl.CourseInfo value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.add(value);
        onChanged();
      } else {
        listBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder addList(
        int index, com.yingshibao.app.idl.CourseInfo value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.add(index, value);
        onChanged();
      } else {
        listBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder addList(
        com.yingshibao.app.idl.CourseInfo.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.add(builderForValue.build());
        onChanged();
      } else {
        listBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder addList(
        int index, com.yingshibao.app.idl.CourseInfo.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.add(index, builderForValue.build());
        onChanged();
      } else {
        listBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder addAllList(
        java.lang.Iterable<? extends com.yingshibao.app.idl.CourseInfo> values) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
      } else {
        listBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder clearList() {
      if (listBuilder_ == null) {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        listBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public Builder removeList(int index) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.remove(index);
        onChanged();
      } else {
        listBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public com.yingshibao.app.idl.CourseInfo.Builder getListBuilder(
        int index) {
      return getListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public com.yingshibao.app.idl.CourseInfoOrBuilder getListOrBuilder(
        int index) {
      if (listBuilder_ == null) {
        return list_.get(index);  } else {
        return listBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public java.util.List<? extends com.yingshibao.app.idl.CourseInfoOrBuilder> 
         getListOrBuilderList() {
      if (listBuilder_ != null) {
        return listBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(list_);
      }
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public com.yingshibao.app.idl.CourseInfo.Builder addListBuilder() {
      return getListFieldBuilder().addBuilder(
          com.yingshibao.app.idl.CourseInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public com.yingshibao.app.idl.CourseInfo.Builder addListBuilder(
        int index) {
      return getListFieldBuilder().addBuilder(
          index, com.yingshibao.app.idl.CourseInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .yingshibao.CourseInfo list = 2;</code>
     *
     * <pre>
     * 课程列表
     * </pre>
     */
    public java.util.List<com.yingshibao.app.idl.CourseInfo.Builder> 
         getListBuilderList() {
      return getListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.yingshibao.app.idl.CourseInfo, com.yingshibao.app.idl.CourseInfo.Builder, com.yingshibao.app.idl.CourseInfoOrBuilder> 
        getListFieldBuilder() {
      if (listBuilder_ == null) {
        listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.yingshibao.app.idl.CourseInfo, com.yingshibao.app.idl.CourseInfo.Builder, com.yingshibao.app.idl.CourseInfoOrBuilder>(
                list_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        list_ = null;
      }
      return listBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:yingshibao.CourseList)
  }

  static {
    defaultInstance = new CourseList(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:yingshibao.CourseList)
}

