// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: module.proto

package com.yingshibao.app.idl;

public final class Module {
  private Module() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_CourseType_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_CourseType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_CourseInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_CourseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_CourseList_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_CourseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_TestAllTypes_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_TestAllTypes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_TestAllTypes_NestedMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_TestAllTypes_NestedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_TestAllTypes_OptionalGroup_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_TestAllTypes_OptionalGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yingshibao_TestAllTypes_RepeatedGroup_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yingshibao_TestAllTypes_RepeatedGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014module.proto\022\nyingshibao\">\n\nCourseType" +
      "\022\022\n\ncourseType\030\001 \002(\r\022\013\n\003num\030\002 \002(\r\022\017\n\007pag" +
      "eNum\030\003 \002(\r\"_\n\nCourseInfo\022\n\n\002id\030\001 \002(\005\022\014\n\004" +
      "name\030\002 \002(\t\022\023\n\013teacherName\030\003 \002(\t\022\r\n\005price" +
      "\030\004 \002(\005\022\023\n\013descritpion\030\005 \002(\t\"?\n\nCourseLis" +
      "t\022\013\n\003num\030\001 \002(\005\022$\n\004list\030\002 \003(\0132\026.yingshiba" +
      "o.CourseInfo\"\222\022\n\014TestAllTypes\022\026\n\016optiona" +
      "l_int32\030\001 \001(\005\022\026\n\016optional_int64\030\002 \001(\003\022\027\n" +
      "\017optional_uint32\030\003 \001(\r\022\027\n\017optional_uint6" +
      "4\030\004 \001(\004\022\027\n\017optional_sint32\030\005 \001(\021\022\027\n\017opti",
      "onal_sint64\030\006 \001(\022\022\030\n\020optional_fixed32\030\007 " +
      "\001(\007\022\030\n\020optional_fixed64\030\010 \001(\006\022\031\n\021optiona" +
      "l_sfixed32\030\t \001(\017\022\031\n\021optional_sfixed64\030\n " +
      "\001(\020\022\026\n\016optional_float\030\013 \001(\002\022\027\n\017optional_" +
      "double\030\014 \001(\001\022\025\n\roptional_bool\030\r \001(\010\022\027\n\017o" +
      "ptional_string\030\016 \001(\t\022\026\n\016optional_bytes\030\017" +
      " \001(\014\022=\n\roptionalgroup\030\020 \001(\n2&.yingshibao" +
      ".TestAllTypes.OptionalGroup\022G\n\027optional_" +
      "nested_message\030\022 \001(\0132&.yingshibao.TestAl" +
      "lTypes.NestedMessage\022A\n\024optional_nested_",
      "enum\030\025 \001(\0162#.yingshibao.TestAllTypes.Nes" +
      "tedEnum\022!\n\025optional_string_piece\030\030 \001(\tB\002" +
      "\010\002\022\031\n\roptional_cord\030\031 \001(\tB\002\010\001\022I\n\025optiona" +
      "l_lazy_message\030\033 \001(\0132&.yingshibao.TestAl" +
      "lTypes.NestedMessageB\002(\001\022\026\n\016repeated_int" +
      "32\030\037 \003(\005\022\026\n\016repeated_int64\030  \003(\003\022\027\n\017repe" +
      "ated_uint32\030! \003(\r\022\027\n\017repeated_uint64\030\" \003" +
      "(\004\022\027\n\017repeated_sint32\030# \003(\021\022\027\n\017repeated_" +
      "sint64\030$ \003(\022\022\030\n\020repeated_fixed32\030% \003(\007\022\030" +
      "\n\020repeated_fixed64\030& \003(\006\022\031\n\021repeated_sfi",
      "xed32\030\' \003(\017\022\031\n\021repeated_sfixed64\030( \003(\020\022\026" +
      "\n\016repeated_float\030) \003(\002\022\027\n\017repeated_doubl" +
      "e\030* \003(\001\022\025\n\rrepeated_bool\030+ \003(\010\022\027\n\017repeat" +
      "ed_string\030, \003(\t\022\026\n\016repeated_bytes\030- \003(\014\022" +
      "=\n\rrepeatedgroup\030. \003(\n2&.yingshibao.Test" +
      "AllTypes.RepeatedGroup\022G\n\027repeated_neste" +
      "d_message\0300 \003(\0132&.yingshibao.TestAllType" +
      "s.NestedMessage\022A\n\024repeated_nested_enum\030" +
      "3 \003(\0162#.yingshibao.TestAllTypes.NestedEn" +
      "um\022!\n\025repeated_string_piece\0306 \003(\tB\002\010\002\022\031\n",
      "\rrepeated_cord\0307 \003(\tB\002\010\001\022I\n\025repeated_laz" +
      "y_message\0309 \003(\0132&.yingshibao.TestAllType" +
      "s.NestedMessageB\002(\001\022\031\n\rdefault_int32\030= \001" +
      "(\005:\00241\022\031\n\rdefault_int64\030> \001(\003:\00242\022\032\n\016def" +
      "ault_uint32\030? \001(\r:\00243\022\032\n\016default_uint64\030" +
      "@ \001(\004:\00244\022\033\n\016default_sint32\030A \001(\021:\003-45\022\032" +
      "\n\016default_sint64\030B \001(\022:\00246\022\033\n\017default_fi" +
      "xed32\030C \001(\007:\00247\022\033\n\017default_fixed64\030D \001(\006" +
      ":\00248\022\034\n\020default_sfixed32\030E \001(\017:\00249\022\035\n\020de" +
      "fault_sfixed64\030F \001(\020:\003-50\022\033\n\rdefault_flo",
      "at\030G \001(\002:\00451.5\022\035\n\016default_double\030H \001(\001:\005" +
      "52000\022\032\n\014default_bool\030I \001(\010:\004true\022\035\n\016def" +
      "ault_string\030J \001(\t:\005hello\022\034\n\rdefault_byte" +
      "s\030K \001(\014:\005world\022E\n\023default_nested_enum\030Q " +
      "\001(\0162#.yingshibao.TestAllTypes.NestedEnum" +
      ":\003BAR\022%\n\024default_string_piece\030T \001(\t:\003abc" +
      "B\002\010\002\022\035\n\014default_cord\030U \001(\t:\003123B\002\010\001\022\026\n\014o" +
      "neof_uint32\030o \001(\rH\000\022F\n\024oneof_nested_mess" +
      "age\030p \001(\0132&.yingshibao.TestAllTypes.Nest" +
      "edMessageH\000\022\026\n\014oneof_string\030q \001(\tH\000\022\025\n\013o",
      "neof_bytes\030r \001(\014H\000\032\033\n\rNestedMessage\022\n\n\002b" +
      "b\030\001 \001(\005\032\032\n\rOptionalGroup\022\t\n\001a\030\021 \001(\005\032\032\n\rR" +
      "epeatedGroup\022\t\n\001a\030/ \001(\005\"9\n\nNestedEnum\022\007\n" +
      "\003FOO\020\001\022\007\n\003BAR\020\002\022\007\n\003BAZ\020\003\022\020\n\003NEG\020\377\377\377\377\377\377\377\377" +
      "\377\001B\r\n\013oneof_fieldB\032\n\026com.yingshibao.app." +
      "idlP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_yingshibao_CourseType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yingshibao_CourseType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_CourseType_descriptor,
        new java.lang.String[] { "CourseType", "Num", "PageNum", });
    internal_static_yingshibao_CourseInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yingshibao_CourseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_CourseInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "TeacherName", "Price", "Descritpion", });
    internal_static_yingshibao_CourseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_yingshibao_CourseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_CourseList_descriptor,
        new java.lang.String[] { "Num", "List", });
    internal_static_yingshibao_TestAllTypes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_yingshibao_TestAllTypes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_TestAllTypes_descriptor,
        new java.lang.String[] { "OptionalInt32", "OptionalInt64", "OptionalUint32", "OptionalUint64", "OptionalSint32", "OptionalSint64", "OptionalFixed32", "OptionalFixed64", "OptionalSfixed32", "OptionalSfixed64", "OptionalFloat", "OptionalDouble", "OptionalBool", "OptionalString", "OptionalBytes", "OptionalGroup", "OptionalNestedMessage", "OptionalNestedEnum", "OptionalStringPiece", "OptionalCord", "OptionalLazyMessage", "RepeatedInt32", "RepeatedInt64", "RepeatedUint32", "RepeatedUint64", "RepeatedSint32", "RepeatedSint64", "RepeatedFixed32", "RepeatedFixed64", "RepeatedSfixed32", "RepeatedSfixed64", "RepeatedFloat", "RepeatedDouble", "RepeatedBool", "RepeatedString", "RepeatedBytes", "RepeatedGroup", "RepeatedNestedMessage", "RepeatedNestedEnum", "RepeatedStringPiece", "RepeatedCord", "RepeatedLazyMessage", "DefaultInt32", "DefaultInt64", "DefaultUint32", "DefaultUint64", "DefaultSint32", "DefaultSint64", "DefaultFixed32", "DefaultFixed64", "DefaultSfixed32", "DefaultSfixed64", "DefaultFloat", "DefaultDouble", "DefaultBool", "DefaultString", "DefaultBytes", "DefaultNestedEnum", "DefaultStringPiece", "DefaultCord", "OneofUint32", "OneofNestedMessage", "OneofString", "OneofBytes", "OneofField", });
    internal_static_yingshibao_TestAllTypes_NestedMessage_descriptor =
      internal_static_yingshibao_TestAllTypes_descriptor.getNestedTypes().get(0);
    internal_static_yingshibao_TestAllTypes_NestedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_TestAllTypes_NestedMessage_descriptor,
        new java.lang.String[] { "Bb", });
    internal_static_yingshibao_TestAllTypes_OptionalGroup_descriptor =
      internal_static_yingshibao_TestAllTypes_descriptor.getNestedTypes().get(1);
    internal_static_yingshibao_TestAllTypes_OptionalGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_TestAllTypes_OptionalGroup_descriptor,
        new java.lang.String[] { "A", });
    internal_static_yingshibao_TestAllTypes_RepeatedGroup_descriptor =
      internal_static_yingshibao_TestAllTypes_descriptor.getNestedTypes().get(2);
    internal_static_yingshibao_TestAllTypes_RepeatedGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yingshibao_TestAllTypes_RepeatedGroup_descriptor,
        new java.lang.String[] { "A", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
