// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

public interface ImportMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yingshibao.ImportMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
   */
  boolean hasCourseInfo();
  /**
   * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
   */
  com.yingshibao.app.idl.CourseInfo getCourseInfo();
  /**
   * <code>optional .yingshibao.CourseInfo courseInfo = 1;</code>
   */
  com.yingshibao.app.idl.CourseInfoOrBuilder getCourseInfoOrBuilder();

  /**
   * <code>optional .yingshibao.CourseList courseList = 2;</code>
   */
  boolean hasCourseList();
  /**
   * <code>optional .yingshibao.CourseList courseList = 2;</code>
   */
  com.yingshibao.app.idl.CourseList getCourseList();
  /**
   * <code>optional .yingshibao.CourseList courseList = 2;</code>
   */
  com.yingshibao.app.idl.CourseListOrBuilder getCourseListOrBuilder();
}
