// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yingshibao.proto

package com.yingshibao.app.idl;

/**
 * Protobuf type {@code yingshibao.UserInfo}
 *
 * <pre>
 * 用户注册请求信息
 * </pre>
 */
public final class UserInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:yingshibao.UserInfo)
    UserInfoOrBuilder {
  // Use UserInfo.newBuilder() to construct.
  private UserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UserInfo defaultInstance;
  public static UserInfo getDefaultInstance() {
    return defaultInstance;
  }

  public UserInfo getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UserInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            nickName_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            schoolName_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            phone_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            examType_ = input.readUInt32();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            channelName_ = bs;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_UserInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_UserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yingshibao.app.idl.UserInfo.class, com.yingshibao.app.idl.UserInfo.Builder.class);
  }

  public static com.google.protobuf.Parser<UserInfo> PARSER =
      new com.google.protobuf.AbstractParser<UserInfo>() {
    public UserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserInfo(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfo> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int NICKNAME_FIELD_NUMBER = 1;
  private java.lang.Object nickName_;
  /**
   * <code>required string nickName = 1;</code>
   *
   * <pre>
   * 
   * 昵称
   * </pre>
   */
  public boolean hasNickName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string nickName = 1;</code>
   *
   * <pre>
   * 
   * 昵称
   * </pre>
   */
  public java.lang.String getNickName() {
    java.lang.Object ref = nickName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        nickName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string nickName = 1;</code>
   *
   * <pre>
   * 
   * 昵称
   * </pre>
   */
  public com.google.protobuf.ByteString
      getNickNameBytes() {
    java.lang.Object ref = nickName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHOOLNAME_FIELD_NUMBER = 2;
  private java.lang.Object schoolName_;
  /**
   * <code>optional string schoolName = 2;</code>
   *
   * <pre>
   * 学校名称
   * </pre>
   */
  public boolean hasSchoolName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string schoolName = 2;</code>
   *
   * <pre>
   * 学校名称
   * </pre>
   */
  public java.lang.String getSchoolName() {
    java.lang.Object ref = schoolName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        schoolName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string schoolName = 2;</code>
   *
   * <pre>
   * 学校名称
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSchoolNameBytes() {
    java.lang.Object ref = schoolName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schoolName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 3;
  private java.lang.Object phone_;
  /**
   * <code>required string phone = 3;</code>
   *
   * <pre>
   * 手机号码
   * </pre>
   */
  public boolean hasPhone() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string phone = 3;</code>
   *
   * <pre>
   * 手机号码
   * </pre>
   */
  public java.lang.String getPhone() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        phone_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string phone = 3;</code>
   *
   * <pre>
   * 手机号码
   * </pre>
   */
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    java.lang.Object ref = phone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXAMTYPE_FIELD_NUMBER = 4;
  private int examType_;
  /**
   * <code>required uint32 examType = 4;</code>
   *
   * <pre>
   * 考试类型 
   * </pre>
   */
  public boolean hasExamType() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required uint32 examType = 4;</code>
   *
   * <pre>
   * 考试类型 
   * </pre>
   */
  public int getExamType() {
    return examType_;
  }

  public static final int CHANNELNAME_FIELD_NUMBER = 5;
  private java.lang.Object channelName_;
  /**
   * <code>required string channelName = 5;</code>
   *
   * <pre>
   * 用户来源渠道
   * </pre>
   */
  public boolean hasChannelName() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required string channelName = 5;</code>
   *
   * <pre>
   * 用户来源渠道
   * </pre>
   */
  public java.lang.String getChannelName() {
    java.lang.Object ref = channelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        channelName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string channelName = 5;</code>
   *
   * <pre>
   * 用户来源渠道
   * </pre>
   */
  public com.google.protobuf.ByteString
      getChannelNameBytes() {
    java.lang.Object ref = channelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    nickName_ = "";
    schoolName_ = "";
    phone_ = "";
    examType_ = 0;
    channelName_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasNickName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPhone()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasExamType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasChannelName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNickNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSchoolNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getPhoneBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeUInt32(4, examType_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getChannelNameBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNickNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSchoolNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getPhoneBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, examType_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getChannelNameBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.yingshibao.app.idl.UserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.UserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.yingshibao.app.idl.UserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.yingshibao.app.idl.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.yingshibao.app.idl.UserInfo prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yingshibao.UserInfo}
   *
   * <pre>
   * 用户注册请求信息
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yingshibao.UserInfo)
      com.yingshibao.app.idl.UserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yingshibao.app.idl.UserInfo.class, com.yingshibao.app.idl.UserInfo.Builder.class);
    }

    // Construct using com.yingshibao.app.idl.UserInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      nickName_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      schoolName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      phone_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      examType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      channelName_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yingshibao.app.idl.Yingshibao.internal_static_yingshibao_UserInfo_descriptor;
    }

    public com.yingshibao.app.idl.UserInfo getDefaultInstanceForType() {
      return com.yingshibao.app.idl.UserInfo.getDefaultInstance();
    }

    public com.yingshibao.app.idl.UserInfo build() {
      com.yingshibao.app.idl.UserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.yingshibao.app.idl.UserInfo buildPartial() {
      com.yingshibao.app.idl.UserInfo result = new com.yingshibao.app.idl.UserInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.nickName_ = nickName_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.schoolName_ = schoolName_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.phone_ = phone_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.examType_ = examType_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.channelName_ = channelName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yingshibao.app.idl.UserInfo) {
        return mergeFrom((com.yingshibao.app.idl.UserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yingshibao.app.idl.UserInfo other) {
      if (other == com.yingshibao.app.idl.UserInfo.getDefaultInstance()) return this;
      if (other.hasNickName()) {
        bitField0_ |= 0x00000001;
        nickName_ = other.nickName_;
        onChanged();
      }
      if (other.hasSchoolName()) {
        bitField0_ |= 0x00000002;
        schoolName_ = other.schoolName_;
        onChanged();
      }
      if (other.hasPhone()) {
        bitField0_ |= 0x00000004;
        phone_ = other.phone_;
        onChanged();
      }
      if (other.hasExamType()) {
        setExamType(other.getExamType());
      }
      if (other.hasChannelName()) {
        bitField0_ |= 0x00000010;
        channelName_ = other.channelName_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasNickName()) {
        
        return false;
      }
      if (!hasPhone()) {
        
        return false;
      }
      if (!hasExamType()) {
        
        return false;
      }
      if (!hasChannelName()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.yingshibao.app.idl.UserInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.yingshibao.app.idl.UserInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object nickName_ = "";
    /**
     * <code>required string nickName = 1;</code>
     *
     * <pre>
     * 
     * 昵称
     * </pre>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string nickName = 1;</code>
     *
     * <pre>
     * 
     * 昵称
     * </pre>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string nickName = 1;</code>
     *
     * <pre>
     * 
     * 昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string nickName = 1;</code>
     *
     * <pre>
     * 
     * 昵称
     * </pre>
     */
    public Builder setNickName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      nickName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string nickName = 1;</code>
     *
     * <pre>
     * 
     * 昵称
     * </pre>
     */
    public Builder clearNickName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      nickName_ = getDefaultInstance().getNickName();
      onChanged();
      return this;
    }
    /**
     * <code>required string nickName = 1;</code>
     *
     * <pre>
     * 
     * 昵称
     * </pre>
     */
    public Builder setNickNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      nickName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object schoolName_ = "";
    /**
     * <code>optional string schoolName = 2;</code>
     *
     * <pre>
     * 学校名称
     * </pre>
     */
    public boolean hasSchoolName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string schoolName = 2;</code>
     *
     * <pre>
     * 学校名称
     * </pre>
     */
    public java.lang.String getSchoolName() {
      java.lang.Object ref = schoolName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          schoolName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string schoolName = 2;</code>
     *
     * <pre>
     * 学校名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSchoolNameBytes() {
      java.lang.Object ref = schoolName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schoolName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string schoolName = 2;</code>
     *
     * <pre>
     * 学校名称
     * </pre>
     */
    public Builder setSchoolName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      schoolName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string schoolName = 2;</code>
     *
     * <pre>
     * 学校名称
     * </pre>
     */
    public Builder clearSchoolName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      schoolName_ = getDefaultInstance().getSchoolName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string schoolName = 2;</code>
     *
     * <pre>
     * 学校名称
     * </pre>
     */
    public Builder setSchoolNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      schoolName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone_ = "";
    /**
     * <code>required string phone = 3;</code>
     *
     * <pre>
     * 手机号码
     * </pre>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string phone = 3;</code>
     *
     * <pre>
     * 手机号码
     * </pre>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string phone = 3;</code>
     *
     * <pre>
     * 手机号码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string phone = 3;</code>
     *
     * <pre>
     * 手机号码
     * </pre>
     */
    public Builder setPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      phone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string phone = 3;</code>
     *
     * <pre>
     * 手机号码
     * </pre>
     */
    public Builder clearPhone() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phone_ = getDefaultInstance().getPhone();
      onChanged();
      return this;
    }
    /**
     * <code>required string phone = 3;</code>
     *
     * <pre>
     * 手机号码
     * </pre>
     */
    public Builder setPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      phone_ = value;
      onChanged();
      return this;
    }

    private int examType_ ;
    /**
     * <code>required uint32 examType = 4;</code>
     *
     * <pre>
     * 考试类型 
     * </pre>
     */
    public boolean hasExamType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 examType = 4;</code>
     *
     * <pre>
     * 考试类型 
     * </pre>
     */
    public int getExamType() {
      return examType_;
    }
    /**
     * <code>required uint32 examType = 4;</code>
     *
     * <pre>
     * 考试类型 
     * </pre>
     */
    public Builder setExamType(int value) {
      bitField0_ |= 0x00000008;
      examType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint32 examType = 4;</code>
     *
     * <pre>
     * 考试类型 
     * </pre>
     */
    public Builder clearExamType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      examType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object channelName_ = "";
    /**
     * <code>required string channelName = 5;</code>
     *
     * <pre>
     * 用户来源渠道
     * </pre>
     */
    public boolean hasChannelName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string channelName = 5;</code>
     *
     * <pre>
     * 用户来源渠道
     * </pre>
     */
    public java.lang.String getChannelName() {
      java.lang.Object ref = channelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string channelName = 5;</code>
     *
     * <pre>
     * 用户来源渠道
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      java.lang.Object ref = channelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string channelName = 5;</code>
     *
     * <pre>
     * 用户来源渠道
     * </pre>
     */
    public Builder setChannelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      channelName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string channelName = 5;</code>
     *
     * <pre>
     * 用户来源渠道
     * </pre>
     */
    public Builder clearChannelName() {
      bitField0_ = (bitField0_ & ~0x00000010);
      channelName_ = getDefaultInstance().getChannelName();
      onChanged();
      return this;
    }
    /**
     * <code>required string channelName = 5;</code>
     *
     * <pre>
     * 用户来源渠道
     * </pre>
     */
    public Builder setChannelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      channelName_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:yingshibao.UserInfo)
  }

  static {
    defaultInstance = new UserInfo(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:yingshibao.UserInfo)
}

